### ISSUE TITLE
docker-compose failure

### ISSUE THREAD

**Issue by sahabulh** [citrineos/citrineos#10]
I have all the pre-setup requirements fullfilled as listed [here](https://citrineos.github.io/pre-setup.html) and am following the quickstart guide detailed [here](https://citrineos.github.io/quickstart.html).

**System details:**
Ubuntu 20.04
Node.js v20.5.0
npm 9.8.1
docker 24.0.7, build afdd53b
docker-compose 1.25.0, build unknown

**Issue**
The `./unix-init-install-all.sh` command runs perfectly. I have attached the build log. Problem occurs when I run the `docker-compose up -d` command. Here is the ouput:
> ERROR: The Compose file './docker-compose.yml' is invalid because:
services.citrine.depends_on contains an invalid type, it should be an array

what is wrong and how can I fix this?

**Comment by thanaParis** [comment]
Hi @sahabulh ! [After some research](https://stackoverflow.com/questions/71060072/docker-compose-depends-on-with-condition-invalid-type-should-be-an-array), it seems that the issue is with not using Docker V2, which can be done by using `docker compose` instead of `docker-compose`. Please try that and let me know if the issue persists!
