### ISSUE TITLE
Issues with "Components Variable"

### ISSUE THREAD

**Issue by DylanVautrin** [citrineos/citrineos#25]
Hello,
I have an issue with my CitrineOS running, everything is fine but i don't have access to "Componenents Varialble" module : 
![image](https://github.com/citrineos/citrineos/assets/87700854/7bc216f8-8764-49d2-b681-46e504d9f192)

Did i make a mistake during the build ? 
Thanks !

**Comment by yuvenus** [comment]
Hello Dylan, you didn't make any mistake in your build, don't worry! The Directus UI does not properly display junction tables such as `ComponentVariable`, because there is no ID in the table, which is caused by Sequelize creating compound index off the two existing columns, `componentId` and `variableId`, rather than using an ID as the primary key. 

Unfortunately, we can't fix the Directus display as a result 😔 If you need to view the contents of this table, the best way would be through a database GUI. In general, you shouldn't need to directly add items to this table, but you can do so through a database GUI in case of emergency.

Please let us know if you have any more questions, and if not, please let us know if this issue can be closed. Thank you!

**Comment by DylanVautrin** [comment]
Oh okay, then i close this issue if it is okay ! 
Thanks :)
